[tool.poetry]
name = "raycast-scripts"
version = "0.1.0"
description = ""
authors = ["Shawn Koh <shawn@shawnkoh.sg>"]

[tool.poetry.dependencies]
python = "^3.9"
Markdown = "^3.3.4"
beautifulsoup4 = "^4.10.0"
aqt = {extras = ["qt6"], version = "^2.1.49"}
lxml = "^4.6.3"
regex = "^2021.10.23"
unmarkd = "^0.1.7"
psutil = "^5.8.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
hypothesis = "^6.24.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
